version: '3.8'

services:
  web:
    container_name: cicdaws_web
    build: .
    restart: always
    command: gunicorn cicdaws.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    # expose:
    #   - 8000
    ports:
      - "8000:8000"
    env_file:
      - .env

    
  nginx:
    container_name: cicdaws_nginx
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/code/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

  
volumes:
  # postgres_data:
  static_volume: